const flights = [{
      //indexNumber:1,
      tailNumber:'YUG',
      acName:'Puchacz',
      p1FName:'John',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      launchFee:'4.50',
      soaringFee:'0.15'
      },{
      //indexNumber:2,
      tailNumber:'TUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      launchFee:'4.50',
      soaringFee:'0.15'
      },{
      //indexNumber:3,
      tailNumber:'PUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      launchFee:'4.50',
      soaringFee:'0.15'
      },{
      //indexNumber:4,
      tailNumber:'AUG',
      acName:'K13',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      launchFee:'4.50',
      soaringFee:'0.15'
      },{
      //indexNumber:5,
      tailNumber:'TUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      launchFee:'4.50',
      soaringFee:'0.15'
      },{
      //indexNumber:6,
      tailNumber:'PUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      launchFee:'4.50',
      soaringFee:'0.15'
      },{
      //indexNumber:7,
      tailNumber:'AUG',
      acName:'K13',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      launchFee:'4.50',
      soaringFee:'0.15'
      },{
      //indexNumber:8,
      tailNumber:'TUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      launchFee:'4.50',
      soaringFee:'0.15'
      },{
      //indexNumber:9,
      tailNumber:'PUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      launchFee:'4.50',
      soaringFee:'0.15'
      },{
      //indexNumber:10,
      tailNumber:'AUG',
      acName:'K13',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      launchFee:'4.50',
      soaringFee:'0.15'
      },{
      //indexNumber:11,
      tailNumber:'TUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      launchFee:'4.50',
      soaringFee:'0.15'
      },{
      //indexNumber:12,
      tailNumber:'PUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      launchFee:'4.50',
      soaringFee:'0.15'
      },{
      //indexNumber:13,
      tailNumber:'AUG',
      acName:'K13',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      launchFee:'4.50',
      soaringFee:'0.15'
      }]

export default flights