const flights = [{
      flightNumber:1,
      tailNumber:'YUG',
      acName:'Puchacz',
      p1FName:'John',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      lFee:'4.50',
      sFee:'0.15'
      },{
      flightNumber:2,
      tailNumber:'TUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      lFee:'4.50',
      sFee:'0.15'
      },{
      flightNumber:3,
      tailNumber:'PUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      lFee:'4.50',
      sFee:'0.15'
      },{
      flightNumber:4,
      tailNumber:'AUG',
      acName:'K13',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      lFee:'4.50',
      sFee:'0.15'
      },{
      flightNumber:5,
      tailNumber:'TUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      lFee:'4.50',
      sFee:'0.15'
      },{
      flightNumber:6,
      tailNumber:'PUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      lFee:'4.50',
      sFee:'0.15'
      },{
      flightNumber:7,
      tailNumber:'AUG',
      acName:'K13',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      lFee:'4.50',
      sFee:'0.15'
      },{
      flightNumber:8,
      tailNumber:'TUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      lFee:'4.50',
      sFee:'0.15'
      },{
      flightNumber:9,
      tailNumber:'PUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      lFee:'4.50',
      sFee:'0.15'
      },{
      flightNumber:10,
      tailNumber:'AUG',
      acName:'K13',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      lFee:'4.50',
      sFee:'0.15'
      },{
      flightNumber:11,
      tailNumber:'TUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      lFee:'4.50',
      sFee:'0.15'
      },{
      flightNumber:12,
      tailNumber:'PUG',
      acName:'Puchacz',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      lFee:'4.50',
      sFee:'0.15'
      },{
      flightNumber:13,
      tailNumber:'AUG',
      acName:'K13',
      p1FName:'Jack',
      p1LName:'Smith',
      p2FName:'Jack',
      p2LName:'Bing',
      lFee:'4.50',
      sFee:'0.15'
      }]

export default flights